# Generated by Django 4.0.1 on 2022-01-10 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_pessoa_alter_evento_data_criacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='endereco',
            field=models.TextField(max_length=120, null=True),
        ),
    ]
